feature:
  - head-branch: '^feature/.*$'
  - head-branch: '^feat/.*$'

bugfix:
  - head-branch: '^bugfix/.*$'
  - head-branch: '^fix/.*$'

refactor:
  - head-branch: '^refactor/.*$'

chore:
  - head-branch: '^chore/.*$'