name: Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [develop]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Label the PR
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"