name: Custom Branch Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [develop]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Label PR based on branch name
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const prNumber = context.payload.pull_request.number;
            
            let labels = [];
            
            if (branchName.startsWith('feature/') || branchName.startsWith('feat/')) {
              labels.push('feature');
            } else if (branchName.startsWith('bugfix/') || branchName.startsWith('fix/')) {
              labels.push('bugfix');
            } else if (branchName.startsWith('refactor/')) {
              labels.push('refactor');
            } else if (branchName.startsWith('chore/')) {
              labels.push('chore');
            }
            
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: labels
              });
              
              console.log(`Added labels: ${labels.join(', ')} to PR #${prNumber}`);
            } else {
              console.log(`No matching labels found for branch: ${branchName}`);
            }