name: Sync Branches

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - main

jobs:
  add-hotfix-label:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
      - name: Add HOTFIX label to PR
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['hotfix']
            });
            console.log('Added "hotfix" label to PR #' + context.payload.pull_request.number);
  syncing:
    name: Sync branches
    if: startsWith(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest
    env:
      FROM_BRANCH: ${{ github.base_ref }}

    steps:
      - name: Define destiny branch
        run: echo "BRANCH=develop" >> $GITHUB_ENV

      - name: Define PR title
        run: echo "TITLE=Sincronizando master -> develop" >> $GITHUB_ENV

      - name: Define PR body
        run: echo "BODY=PR criada automaticamente para sincronização entre branches após hotfix" >> $GITHUB_ENV

      - name: Creating the PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "${{ env.FROM_BRANCH }}",
              base: "${{ env.BRANCH }}",
              title: "${{ env.TITLE }}",
              body: "${{ env.BODY }}"
            })