name: Updates PR Name to release-month-year

on:
  pull_request:
    types: [opened]
    branches: [master, main]

permissions:
  pull-requests: write

jobs:
  update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Atualiza o título da PR para release-DD-MM-YY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          DIA=$(date +"%d")
          MES=$(date +"%m")
          ANO=$(date +"%y")
          gh pr edit "$PR_URL" --title "release-${DIA}-${MES}-${ANO}"