name: Validate PR Source Branch
on:
  pull_request:
    branches: [ main, master ]

jobs:
  validate-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        id: validate
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          echo "Source branch: $SOURCE_BRANCH"
          
          if [[ "$SOURCE_BRANCH" == "develop" ]] || [[ "$SOURCE_BRANCH" == hotfix* ]]; then
            echo "✅ Valid source branch: $SOURCE_BRANCH"
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ Invalid source branch: $SOURCE_BRANCH"
            echo "PRs to main must come from 'develop' or branches starting with 'hotfix'"
            echo "status=failure" >> $GITHUB_OUTPUT
            exit 1
          fi
      
      - name: Comment on PR (if validation fails)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Branch Validation Failed**\n\nThis PR cannot be merged because it originates from an invalid source branch.\n\n**Allowed source branches:**\n- `develop`\n- `hotfix/*`\n\n**Current source branch:** `${{ github.head_ref }}`\n\nPlease create your PR from a valid source branch.'
            })